### PR TITLE
[Breaking] neo6502: Partially update API bindings, fix UExt functions, fix inden…

### PR DESCRIPTION
**Pull request by asiekierka**
…tation

The Mouse, Blitter and some Graphics/Sound functions have not been implemented; the PR consists of the low-hanging fruit, and I'm not sure how much interest remains.

### CODE REVIEW

**Comment by mysterymath** [comment]
This contains some breaking changes, so this change should definitely have the `[Breaking]` tag.

**Review by mysterymath — APPROVED** [review]
Other than the `[Breaking]` tag, LGTM.

**Comment by mysterymath** [comment]
Oh right I can do the edit myself.

**Comment by asiekierka** [comment]
Thanks! Sorry for not getting around to it.

**Pull request merged**
