### PR TITLE
Atari implementation of getchar().

### PR DESCRIPTION
**Pull request by pfusik**
Please comment my attempt to implement `getchar` on the Atari.

It has the following problems:

1. `getchar.c:14:1: warning: unused label 'error' [-Wunused-label]`
What's worse, the optimizer assumes the result is non-negative.

2. `bmi error` jumps to the beginning of the routine:

```asm
    201A: A2 05             LDX #$05
    201C: 8E 42 03          STX ICCMD
    201F: A0 00             LDY #$00
    2021: 8C 48 03          STY ICBLL
    2024: A2 00             LDX #$00
    2026: 86 82             STX $82
    2028: 8C 49 03          STY ICBLH
    202B: A2 00             LDX #$00
    202D: 20 56 E4          JSR CIOV
    2030: 30 E8             BMI $201A
    2032: C9 9B             CMP #$9B
    2034: D0 02             BNE $2038
    2036: A9 0A             LDA #$0A
    2038: A6 82             LDX $82
    203A: 60                RTS
```

I would expect an error if the assembler doesn't understand C labels.

3. As you can see above, there's a spill of constant zero.

I also tried returning from asm, but the compiler complained about missing return value.

### CODE REVIEW

**Comment by pfusik** [comment]
Tried. `clang` seems to not support that.

    getchar.c:12:38: error: expected ')'
        : "=a"(c) : : "p", "a", "x", "y" : error);
                                         ^
    1 error generated.

**Comment by pfusik** [comment]
C:/0/a8/llvm/llvm-mos-sdk/mos-platform/atari8/getchar.s:1:10: error: Could not find include file 'atari.inc'
    .include "atari.inc"
             ^
    ninja: build stopped: subcommand failed.

**Comment by mysterymath** [comment]
Add `target_include_directories(atari8-c PRIVATE .)` to CMakeLists.

**Review by mysterymath — COMMENTED** [review]
Also, one more thing: make sure to add `__attribute__((leaf))` before the getchar declaration in `stdio.h`; otherwise, the compiler would be forced to assume that the assembly language implementation could make arbitrary calls back into the program, since it cannot analyze its contents. This disables static stack and zero page allocation for calling routines.

**Comment by pfusik** [comment]
C implementation with minimal assembly looks good. Inlining does a great job!

For this test:

    #include <stdio.h>

    int main(void) {
      for (;;) {
        int c = getchar();
        if (c < 0)
          break;
        putchar(c);
      }
    }

the `-Os` code is:

    ; main
    2011: 4C 1F 20          JMP $201F
    2014: A2 0A             LDX #$0A   ; would be better:
    2016: C9 9B             CMP #$9B   ; CMP #$9B
    2018: F0 01             BEQ $201B  ; BNE not_eol
    201A: AA                TAX        ; LDA #$0A
    201B: 8A                TXA        ; not_eol:
    201C: 20 37 20          JSR $2037  ; putchar
    201F: A2 07             LDX #$07
    2021: 8E 42 03          STX ICCMD
    2024: A2 00             LDX #$00
    2026: 8E 48 03          STX ICBLL
    2029: 8E 49 03          STX ICBLH
    202C: A2 00             LDX #$00   ; redundant
    202E: 20 56 E4          JSR CIOV
    2031: 10 E1             BPL $2014  ; this is correct, but I would expect CPY #0 first?
    2033: A2 00             LDX #$00   ; can we tell X is preserved by asm?
    2035: 8A                TXA
    2036: 60                RTS

**Comment by mysterymath** [comment]
Nice, ship it!

**Comment by mysterymath** [comment]
Would you mind filing sepearate issues for the various code generation issues here, so I can keep track of them?

In particular the lack of CPY #0 is a compiler bug; there's a pass that deletes redundant comparisons to zero, but there needs to be an explicit exception for inline assembly just like calls, since unlike every other instruction, it can define more than one register "at a time".

**Comment by mysterymath** [comment]
Actually, I was able to add a one line fix for the CMP#0 issue, so no action required there.

**Comment by pfusik** [comment]
Squash it, please. I'll create the optimizer tickets tomorrow.

**Comment by pfusik** [comment]
BTW. what's the easiest way to generate assembly listing from a C file? `-S` outputs IR.

**Comment by mysterymath** [comment]
> BTW. what's the easiest way to generate assembly listing from a C file? `-S` outputs IR.

`-S -fno-lto`

**Comment by mysterymath** [comment]
Thanks for the PR!

**Comment by pfusik** [comment]
Thanks!

Submitted llvm-mos/llvm-mos#243 llvm-mos/llvm-mos#244 llvm-mos/llvm-mos#245 llvm-mos/llvm-mos#246 llvm-mos/llvm-mos#247 for the issues mentioned above.
llvm-mos/llvm-mos#243 is invalid codegen/missing diagnostic, the other are about better codegen.

**Pull request merged**
